#UDP/IXXAT to CAN bridge configuration file
#Sun Jun 28 14:45:58 CEST 2026
codaAutoGrab=true
codaDecimation=1
codaFirstMarkerIndex=1
codaFrameNumber=-1
codaFrameRate=100
codaNBMarkers=1
codaServerIP=localhost
height=809
otFirstMarkerIndex=0
otMulticastIP=239.255.42.99
otNbUnlabeledMarkers=1
otUdpClientIP=localhost
otUdpSourcePort=1511
otUseMulticast=true
selectedTabItem=STREAMIN_OPTIONS
timerFrequency=1
udpClientIP=localhost
udpDestinationPort=15001
udpSourcePort=15000
useCodamotion=false
useIXXAT=false
useOptitrack=false
useTimer=true
useUDP=true
useXSens=false
width=605
xPosition=1315
xSensFrequency=100
xSensSerialNumber=NE3B-79EA-K6RP-WDNH-QA2Y
yPosition=25
