#UDP/IXXAT to CAN bridge configuration file
#Tue Jun 23 13:10:37 CEST 2026
height=1040
selectedSytem=XSENS
useCodamotion=false
useIXXAT=true
useOptitrack=true
useTimer=false
useUDP=false
useXSens=true
width=332
xPosition=1588
yPosition=0
