#UDP/IXXAT to CAN bridge configuration file
#Tue Jun 30 11:55:55 CEST 2026
codaAutoGrab=true
codaDecimation=1
codaFirstMarkerIndex=1
codaFrameNumber=-1
codaFrameRate=100
codaNBMarkers=1
codaServerIP=localhost
height=1040
otFirstMarkerIndex=0
otMulticastIP=239.255.42.99
otNbUnlabeledMarkers=1
otUdpClientIP=localhost
otUdpSourcePort=1511
otUseMulticast=true
selectedTabItem=STREAMIN_OPTIONS
timerFrequency=1
udpClientIP=localhost
udpDestinationPort=15001
udpSourcePort=15000
useCodamotion=false
useIXXAT=false
useOptitrack=false
useTimer=true
useUDP=true
useXSens=false
width=1920
xPosition=0
xSensFrequency=100
xSensSerialNumber=NE3B-79EA-K6RP-WDNH-QA2Y
yPosition=0
